[package]
name = "serve-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "serve a static site from anywhere"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
